"""update user model and setting up foreign key

Revision ID: 5067bfdfd4b9
Revises: 421bd1bfcc4a
Create Date: 2025-06-29 23:13:27.412127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5067bfdfd4b9'
down_revision: Union[str, None] = '421bd1bfcc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('datetime', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_todos_datetime'), 'todos', ['datetime'], unique=False)
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_datetime'), table_name='todos')
    op.drop_column('todos', 'user_id')
    op.drop_column('todos', 'datetime')
    # ### end Alembic commands ###
