"""initial migration

Revision ID: f7ab9f9bc711
Revises: 5966ddce235b
Create Date: 2025-06-22 18:38:16.271423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ab9f9bc711'
down_revision: Union[str, None] = '5966ddce235b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###

